version: "3.3"
services:
  competency:
    image: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$DOCKER_TAG
    container_name: dev-$CI_PROJECT_NAME
    ports:
      - "8083:8083"
    networks:
      net_api:
        ipv4_address: 172.28.0.23
    volumes:
      - ./appsettings.json:/app/appsettings.Development.json
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CERT_PASSWORD
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - ASPNETCORE_URLS=$ASPNETCORE_URLS
networks:
  net_api:
    external: true